apiVersion: batch/v1
kind: Job
metadata:
  name: prep-prometheus-localpv
  namespace: kube-system
spec:
  template:
    spec:
      nodeName: talos-gng-upw
      restartPolicy: OnFailure
      containers:
        - name: prep
          image: busybox:1.36.1
          command: ["sh","-c","mkdir -p /host/var/local-path-provisioner/prometheus-data && chown -R 1000:2000 /host/var/local-path-provisioner/prometheus-data && chmod -R g+rwX /host/var/local-path-provisioner/prometheus-data && ls -ld /host/var/local-path-provisioner/prometheus-data"]
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
            capabilities: { add: ["CHOWN"], drop: ["NET_RAW"] }
          volumeMounts:
            - name: host-var
              mountPath: /host/var
      volumes:
        - name: host-var
          hostPath:
            path: /var
            type: Directory
