apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata: { name: loki-stack, namespace: observability }
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-stack
      version: "2.*"
      sourceRef: { kind: HelmRepository, name: grafana, namespace: flux-system }
  values:
    grafana: { enabled: false }
    loki:
      persistence: { enabled: true, size: 10Gi, storageClassName: local-path }
    promtail:
      enabled: true