apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata: { name: postgres, namespace: trading }
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: "15.*"
      sourceRef: { kind: HelmRepository, name: bitnami, namespace: flux-system }
  values:
    auth:
      username: trader
      password: traderpass
      database: trading
    primary:
      persistence: { enabled: true, size: 20Gi, storageClass: local-path }
      resources: { requests: { cpu: 500m, memory: 1Gi } }