apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: local-path-provisioner
      # pick a known-good version; 0.0.32+ is fine on Pi
      version: ">=0.0.32"
      sourceRef:
        kind: HelmRepository
        name: rancher          # <— must match the name above
        namespace: flux-system
  values:
    storageClass:
      create: true
      defaultClass: true
      name: local-path
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths: ["/var/local-path-provisioner"]
