apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: local-path-provisioner
      version: ">=0.0.33"
      sourceRef:
        kind: HelmRepository
        name: containeroo
        namespace: flux-system
  values:
    storageClass:
      create: true
      defaultClass: true
      name: local-path
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths: ["/var/local-path-provisioner"]
