apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata: { name: kube-prometheus-stack, namespace: observability }
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "57.*"
      sourceRef: { kind: HelmRepository, name: prometheus-community, namespace: flux-system }
  values:
    grafana:
      adminPassword: prom-operator
      persistence: { enabled: true, size: 5Gi, storageClassName: local-path }
    prometheus:
      prometheusSpec:
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              resources: { requests: { storage: 10Gi } }