apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trading
resources:
  - dxfeed-adapter/
  - ib-bridge/
  - backtrader/
  - order-manager/
  - rl-service/
  - streamlit-ui/
patches:
  - target:
      kind: Deployment
      namespace: trading
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"