apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: baseline-allow, namespace: trading }
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [ { podSelector: {} } ]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }
    - to: [ { podSelector: {} } ]
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - { protocol: TCP, port: 9090 }
